### ISSUE TITLE
Use read_wstr to read chat strings

### ISSUE THREAD

**Issue by HybridEidolon** [jtuu/psochatlogaddon#1]
`pso.read_wstr` will read the string as a UTF-16 sequence ended with two null bytes using the Windows API, into a UTF-8 string that can be drawn by ImGui.

However, without CJK fonts loaded, CJK characters won't be drawn. I'm not sure how to solve this because including a CJK font set in the plugin would be prohibitively heavy.

**Comment by jtuu** [comment]
Thanks!
